name: continuous_integration

on: 
  push:
      paths:
        - 'backend/**'
defaults:
  run:
    working-directory: backend

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: "3.11"

      - name: Restore venv from cache
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-

      - name: Create virtual environment if not cached
        run: |
          ls -la
          if [ ! -d "venv" ]; then
            python -m venv venv
            source venv/bin/activate
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -e .
          fi
          ls -la
      
      - name: Save venv to cache
        if: always()
        uses: actions/cache@v3
        with:
          path: venv
          key: ${{ runner.os }}-venv-${{ hashFiles('requirements.txt') }}
   
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: list dir#1
        run: ls -la
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
          python-version: "3.11"
      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
      - name: list dir#2
        run: ls -la
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install bandit semgrep
          pip install -r requirements.txt
          pip install -e .
      - name: Lint with flake8
        run: |
          flake8 . --show-source --statistics
        continue-on-error: true
      - name: run SAST
        run: |
          bandit -r src/modules/
        continue-on-error: true
      - name: Test with pytest
        run: |
          pytest --disable-warnings