name: Frontend CI Workflow

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: frontend

jobs:
  cache:
    name: Generate Cache
    runs-on: ubuntu-latest
    outputs:
      node_modules_cache_key: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Linting
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: npm run test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Build the Application
        run: npm run build
