name: Frontend CI Workflow

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  cache:
    name: Generate Cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore Node Modules Cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
