name: Frontend CI Pipeline

on:
  push:
    paths:
      - 'frontend/**'
  pull_request:
    paths:
      - 'frontend/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run workflow on'
        required: true
        default: 'main'

jobs:
  cache:
    name: Cache Node Modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/frontend/node_modules"
          key: ${{ runner.os }}-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

  lint_and_test:
    name: Run Lint and Tests
    runs-on: ubuntu-latest
    needs: cache
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Lint the project
        run: npm run lint

      - name: Run tests
        run: npm test

  audit:
    name: Run npm audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Run npm audit for vulnerabilities
        run: npm audit

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build the application
        run: npm run build
