name: continuous_integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip 

      - name: Install Dependencies
        run: |
          source venv/bin/activate
          pip install --no-cache-dir -r requirements.txt
          pip install --no-cache-dir -e .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'

      - name: Activate Virtual Environment
        run: |
          source venv/bin/activate

      - name: Run tests
        run: |
          source venv/bin/activate
          pytest
