name: continuous_integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: 'pip'
      
      - name: Install Dependencies
        run: pip install -r .github/workflows/requirements.txt
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
      
      - name: Install Dependencies
        run: 
          pip install -r backend/requirements.txt

      - name: test_script
        run: pytest backend/test.py